# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

#Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main



jobs:
  test:

    runs-on: ubuntu-latest

    steps:
        #Step 1: Check out the code form the repository 
    - uses: actions/checkout@v4
    - name: Set up Python 3.10

        #Step 2: Set up Python Environment
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

        #Step 3: Install Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #Step 4: Run Tests
    - name: Test with pytest
      run: |
        pytest
